class AppKeywordConstants {
  static const List<String> skills = [
    'Accounting',
    'Acting',
    'Administration',
    'Advertising',
    'Agriculture',
    'Animal Care',
    'Art',
    'Blogging',
    'Business Development',
    'Carpentry',
    'Catering',
    'Child Care',
    'Cleaning',
    'Coaching',
    'Communication',
    'Computer Skills',
    'Cooking',
    'Counselling',
    'Crafts',
    'Customer Service',
    'Data Entry',
    'Design',
    'Driving',
    'Editing',
    'Education',
    'Electrical Work',
    'Engineering',
    'Entertainment',
    'Event Planning',
    'Fashion',
    'Finance',
    'First Aid',
    'Fundraising',
    'Gardening',
    'Graphic Design',
    'Health Care',
    'Hospitality',
    'Human Resources',
    'Information Technology',
    'Journalism',
    'Languages',
    'Law',
    'Leadership',
    'Management',
    'Marketing',
    'Media',
    'Medicine',
    'Mentoring',
    'Music',
    'Negotiation',
    'Nursing',
    'Painting',
    'Personal Training',
    'Photography',
    'Plumbing',
    'Problem Solving',
    'Project Management',
    'Public Relations',
    'Public Speaking',
    'Research',
    'Retail',
    'Sales',
    'Secretarial',
    'Security',
    'Social Media',
    'Social Work',
    'Software Development',
    'Sports',
    'Teaching',
    'Teamwork',
    'Technical Support',
    'Telecommunications',
    'Theatre',
    'Tourism',
    'Training',
    'Translation',
    'Transport',
    'Tutoring',
    'Video Production',
    'Web Design',
    'Writing',
  ];

  static const List<String> interests = [
    'Animals',
    'Art',
    'Child Care',
    'Community',
    'Culture',
    'Disability',
    'Education',
    'Elderly',
    'Environment',
    'Health',
    'Homelessness',
    'Human Rights',
    'Mental Health',
    'Music',
    'Politics',
    'Poverty',
    'Refugees',
    'Religion',
    'Science',
    'Social Justice',
    'Sports',
    'Technology',
    'Theatre'
  ];

  static const List<String> daysOfWeek = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday'
  ];
}
